### ISSUE TITLE
调用云函数出错，报500

### ISSUE THREAD

**Issue by csanshi** [Gwokhov/chronus#2]
云函数login调用政策。getGoalList和createGoal调用失败，报500错误。
已经按照你说的配置来了，唯一的疑问是: goals中如何设置_openid为唯一索引啊，好像只能添加索引，无法修改。

**Comment by gwokhov** [comment]
> 云函数login调用政策。getGoalList和createGoal调用失败，报500错误。
> 已经按照你说的配置来了，唯一的疑问是: goals中如何设置_openid为唯一索引啊，好像只能添加索引，无法修改。

现在版本在添加索引时可以设为唯一，报错可以发下具体内容。 @csanshi

**Comment by csanshi** [comment]
那时刚接触小程序，不太懂。其实没什么问题，那个情况是因为我没有将云函数部署上去。
